/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JEBase */

#ifndef _Included_JEBase
#define _Included_JEBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JEBase
 * Method:    doSomething
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JEBase_doSomething
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
